#ifndef CONST_H
#define CONST_H
#include "hal/adc_types.h"

// #define HW01
#define HW02
#define VERBOSE 1
#define ADC_MULTISAMPLE 12
#define DEVICE_NAME "Wirelessifier"
#define FIRMWARE_VERSION "0.1.40"
#define HARDWARE_VERSION "rev. 02"

#ifdef HW01
#define GPIO_MUX_OE 34
#define GPIO_MUX_SEL 33
#define GPIO_WS2812B_PIN GPIO_NUM_38
#define GPIO_BUTTON_SW4 GPIO_NUM_13
#define GPIO_BAT_PGOOD GPIO_NUM_21
#define GPIO_BAT_CHRG GPIO_NUM_37
#define GPIO_5V_EN GPIO_NUM_35
#define GPIO_BAT_CE GPIO_NUM_36
#define NUM_LEDS 17
#endif

#ifdef HW02
#define GPIO_MUX_OE 34
#define GPIO_MUX_SEL 33
#define GPIO_WS2812B_PIN GPIO_NUM_38
#define GPIO_BUTTON_SW4 GPIO_NUM_3
#define GPIO_BUTTON_SW3 GPIO_NUM_2
#define GPIO_BUTTON_SW2 GPIO_NUM_1
#define GPIO_BUTTON_SW1 GPIO_NUM_0
#define GPIO_ROT_A GPIO_NUM_4
#define GPIO_ROT_B GPIO_NUM_13
#define GPIO_ROT_D GPIO_NUM_14
#define GPIO_ROT_E GPIO_NUM_17
#define GPIO_BAT_ISET1 GPIO_NUM_39
#define GPIO_BAT_ISET2 GPIO_NUM_40
#define GPIO_BAT_ISET3 GPIO_NUM_41
#define GPIO_BAT_ISET4 GPIO_NUM_42
#define GPIO_BAT_ISET5 GPIO_NUM_45
#define GPIO_BAT_ISET6 GPIO_NUM_46
#define GPIO_PGOOD GPIO_NUM_21
#define GPIO_BAT_CHRG GPIO_NUM_37
#define GPIO_5V_EN GPIO_NUM_35
#define GPIO_BAT_CE GPIO_NUM_36
#define GPIO_ADC_BAT GPIO_NUM_5
#define ADC_CHAN_BAT ADC_CHANNEL_4
#define GPIO_ADC_VIN GPIO_NUM_6
#define ADC_CHAN_VIN ADC_CHANNEL_5
#define NUM_LEDS 17
#endif

#endif // CONST_H
